### ISSUE TITLE
Add Dusk JavaScript configurations

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-wallet-js#1]
#### Summary
The repo is currently lacking certain foundational configurations which are common to all Dusk JavaScript repositories.  The following configurations are missing:

* package.json
* Dusk eslint configuration
* vitest configuration

**Comment by kieranhall** [comment]
Reopening since these changes have been lost.

**Comment by kieranhall** [comment]
We will have a meeting to discuss more broadly our coding standards and repo hygiene configurations.

**Comment by HDauven** [comment]
No longer relevant as Deno has a linter and code formatter integrated.
