### ISSUE TITLE
Testing is not possible with the wallet-js library

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-wallet-js#15]
There are problems running code from the wallet-js lib connected to the top-level `await`.

**Comment by Daksh14** [comment]
@kieranhall @ascartabelli Try the 0.2.0 version and let me know

**Comment by Daksh14** [comment]
finished by https://github.com/dusk-network/dusk-wallet-js/commit/bb9b623f761cc976e8cee7d6dfaf83072e4fc14e
