### ISSUE TITLE
Compatbility Issue: Async Iterable is not supported in Chrome and Safari

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/dusk-wallet-js#20]
**Describe the bug**
During the sync the async iterator is not supported by various browsers

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#browser_compatibility

**To Reproduce**
Call wallet.sync() in chrome or safari

**Expected behaviour**
The sync should work without error

**Platform**
Fill as appropriate
 - Architecture: arm
 - OS: mac m1
 - Browser Chrome, safari

**Comment by ZER0** [comment]
I think we can close as `wontfix` since we have the polyfill, no? @Daksh14

**Comment by HDauven** [comment]
Resolved by polyfill
