### ISSUE TITLE
Resolve rewards number (convert from LUX to DUX)

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/dusk-wallet-js#22]
Currently, there is an issue with the `withdrawReward` method call on the Wallet instance.

<img width="2167" alt="Screenshot 2023-12-18 at 17 22 23" src="https://github.com/dusk-network/dusk-wallet-js/assets/34094428/1f1318fc-dea2-4737-bdb8-86f658db583c">

Have synced with @Daksh14, apparently the fix is to convert the rewards value from LUX to DUX.

**Comment by Daksh14** [comment]
Fixed by  #24
