### ISSUE TITLE
Wrong condition in the Stake functionality

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/dusk-wallet-js#23]
<img width="2168" alt="Screenshot 2023-12-19 at 14 33 23" src="https://github.com/dusk-network/dusk-wallet-js/assets/34094428/6746cd57-8863-4275-8f71-a5034e22ce98">

<img width="993" alt="Screenshot 2023-12-19 at 14 40 28" src="https://github.com/dusk-network/dusk-wallet-js/assets/34094428/b5c7840b-eca7-47e5-82b6-1e268bea6a86">

Line 84 within the `mod.js` should be `if (index === -1)` instead of `if (!index)`

**Comment by Daksh14** [comment]
Fixed by  #24
