### ISSUE TITLE
Wallet tries to fetch history when it does not exist

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/dusk-wallet-js#33]
Results in TypeError: can't access property "transactions", txRemote.block is null

**Comment by Daksh14** [comment]
Fixed https://github.com/dusk-network/dusk-wallet-js/commit/2efd2af7d5b712c90e5824d81f1e8dbc45745bf2#diff-131cc32c1e2e61ea89e39f368213b6443f4d08f3ce05a4b3aadaaeddf4b4fc6aR87
