### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/dusk-wallet-js#69]
# Epic

## Summary

Refractor code

## Tasks

*List related tasks and their issue numbers.*

- [x] #70
- [ ] #71
- [ ] #72

**Comment by ZER0** [comment]
For the address class, let's still provide the old methods (e.g. `Wallet.getPsks()`) along the new one, so we don't have an immediate breaking change, and the Web Wallet has time to adapt.

**Comment by Fulviuus** [comment]
This is just a collection of issues that can be tackled separately, and does not follow the guidelines for being an epic. Closing.
