### ISSUE TITLE
Introduce publishing for this library

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-wallet-js#8]
#### Summary

In order to integrate with this library, we require it to be published to our private Github package registry.  We need this ASAP in order to start integrating and testing the functionality in the web-wallet.

#### Possible Solution

Each time you merge a PR into the main branch, you (manually) run the `npm` publish command

#### Additional Context

We are doing the same thing for the [`dusk-eslint`](https://github.com/dusk-network/dusk-eslint-config) project, you should be able to follow the same setup (see .npmrc file).

**Comment by Fulviuus** [comment]
@Daksh14 can you look into this?

**Comment by Daksh14** [comment]
We can publish to npm by
```
deno run -A npm.js 0.1.0

cd npm

npm publish
```

With the latest npm.js script
