### ISSUE TITLE
Fix return type of `getSeedFromMnemonic`

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/dusk-wallet-js#9]
The doc comments in the function [`getSeedFromMnemonic`](https://github.com/dusk-network/dusk-wallet-js/blob/main/src/mnemonic.js#L32) state that is returning a `string`, while actually it returns a `number[]`.

This messes up the typing in the web wallet application.

N.B. the `Wallet` constructor wants a `Uint8Array` for the seed parameter.

**Comment by Daksh14** [comment]
Fixed in 92b4ad6
