### ISSUE TITLE
Behavior of sync with parameters and database state

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/dusk-wallet-js#93]

**Comment by ZER0** [comment]
Here's the scenarios we discussed:

| # | sync call              | cache's `last_pos` | sync behavior                             |
| - | ---------------------- | ------------------ | ----------------------------------------- |
| 1 | `sync()`               | `null`             | skip sync                                 |
| 2 | `sync()`               | `0`                | sync from cache's `last_pos` (genesis)                         |
| 3 | `sync()`               | greater than `0`   | sync from cache's `last_pos`              |
| 4| `sync({ from: 0 })`    | `null`             | sync from the value given (genesis)                         |
| 5 | `sync({ from: 0 })`    | `0`                | sync from the value given (genesis)                         |
| 6 | `sync({ from: 0 })`    | greater than `0`   | throw Error                               |
| 7 | `sync({ from: 1234 })` | `null`             | sync from `Max(0, Min(1234, NetworkBlockHeight)`) |
| 8 | `sync({ from: 1234 })` | exists             | throw Error                               |

> [!NOTE]
> -  If the `from` value in scenario `7` equals `NetworkBlockHeight`, the sync might also be skipped.
> - Scenarios `2` and `3` have the same logic.
> - Scenarios `4`, `5`, and `7` have the same logic, however we we can slightly optimize when we pass `0` as value, since we don't need to cap the argument.
> -  Unless an exception is thrown, store the network's `last_pos` / `block_height` for each chunk in the cache at the end of each behavior. This ensures that, if all chunks are stored correctly, the cache will contain the current `last_pos` / `block_height` of the network by the end.

**Comment by ZER0** [comment]
Instead of creating a new issue, I reopened the original one because I noticed that there wasn't a lack of information in the original specs (see my comment on May 13). The implementation that was merged didn't follow the specs; see the last point in the NOTE block.

Therefore this issue wasn't fixed by PR #94, and still need to be fixed.
